apiVersion: v1
data:
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  exec.enabled: "false"
  server.rbac.log.enforce.enable: "false"
  dex.config: |
    connectors:
      - type: saml
        id: saml
        name: saml
        config:
          ssoURL: https://accounts.google.com/o/saml2/idp?idpid=xxx
          entityIssuer: https://argocd.test.com/api/dex/callback
          caData: |
            xxxxx
          redirectURI: https://argocd.test.com/api/dex/callback
          usernameAttr: email
          emailAttr: email
          ssoIssuer: https://accounts.google.com/o/saml2?idpid=xxx
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
