kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc-airflow
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-xxx
  directoryPerms: "700"
  uid: "1001"
  gid: "1001"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc-dataflow
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-xxx
  directoryPerms: "700"
